version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - ${ROOT_PATH}/mounts/prometheus:/etc/prometheus
      - ${ROOT_PATH}/mounts/prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yaml
    networks:
      - local-network

networks:
  local-network:
    name: local-network
    external: true
