version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${ROOT_PATH}/mounts/etc/nginx:/etc/nginx/
      - ${ROOT_PATH}/mounts/opt/ssl:/opt/ssl/
    networks:
      - local-network

networks:
  local-network:
    name: local-network
    external: true
