# docker-compose.yaml
version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins/mounts/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - ./jenkins/mounts/var/run/docker.sock:/var/run/docker.sock
    networks:
      - nestjs-network
  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=$JENKINS_AGENT_SSH_PUBKEY

networks:
  nestjs-network:
    name: nestjs-network
    external: true
