global:
  scrape_interval: 5s
  scrape_timeout: 3s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: applications
    metrics_path: metrics
    static_configs:
      - targets:
          - 'permissions:3000'   
          - 'prometheus:9090'