version: "3.8"

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${ROOT_PATH}/mounts/data/redis:/data
    networks:
      - local-network
  redisinsight:
    image: redislabs/redisinsight:ri-trusted-origins
    ports:
      - 8001:8001
    environment:
      - RITRUSTEDORIGINS=https://redis.network.com
    volumes:
      - ${ROOT_PATH}/mounts/redisinsight:/db
    networks:
      - local-network

networks:
  local-network:
    name: local-network
    external: true
